name: Node Matrix Action
description: Outputs a matrix with the current Node versions.
inputs:
  envs:
    description: Environment mapping
    required: false
    default: |
      prod: master
      dev: dev
      stage: stage
      test: test
  jobs:
    description: List/CSV of jobs to deploy per environment.
    required: false
    default: app
outputs:
  matrix:
    description: Matrix JSON to be used in another job.
runs:
  using: 'node12'
  main: 'dist/index.js'
